/* Auto-generated by genmsg_cpp for file /home/rcle271/ros_workspace/circleFinder/msg/circleEntry.msg */
#ifndef CIRCLEFINDER_MESSAGE_CIRCLEENTRY_H
#define CIRCLEFINDER_MESSAGE_CIRCLEENTRY_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace circleFinder
{
template <class ContainerAllocator>
struct circleEntry_ : public ros::Message
{
  typedef circleEntry_<ContainerAllocator> Type;

  circleEntry_()
  : x(0.0)
  , y(0.0)
  , distance(0.0)
  , theta(0.0)
  , radius(0.0)
  {
  }

  circleEntry_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , distance(0.0)
  , theta(0.0)
  , radius(0.0)
  {
  }

  typedef float _x_type;
  float x;

  typedef float _y_type;
  float y;

  typedef float _distance_type;
  float distance;

  typedef float _theta_type;
  float theta;

  typedef float _radius_type;
  float radius;


private:
  static const char* __s_getDataType_() { return "circleFinder/circleEntry"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "8f570732ed87e134eeda1a3829552b4e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float32 x\n\
float32 y\n\
float32 distance\n\
float32 theta\n\
float32 radius\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, x);
    ros::serialization::serialize(stream, y);
    ros::serialization::serialize(stream, distance);
    ros::serialization::serialize(stream, theta);
    ros::serialization::serialize(stream, radius);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, x);
    ros::serialization::deserialize(stream, y);
    ros::serialization::deserialize(stream, distance);
    ros::serialization::deserialize(stream, theta);
    ros::serialization::deserialize(stream, radius);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(x);
    size += ros::serialization::serializationLength(y);
    size += ros::serialization::serializationLength(distance);
    size += ros::serialization::serializationLength(theta);
    size += ros::serialization::serializationLength(radius);
    return size;
  }

  typedef boost::shared_ptr< ::circleFinder::circleEntry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::circleFinder::circleEntry_<ContainerAllocator>  const> ConstPtr;
}; // struct circleEntry
typedef  ::circleFinder::circleEntry_<std::allocator<void> > circleEntry;

typedef boost::shared_ptr< ::circleFinder::circleEntry> circleEntryPtr;
typedef boost::shared_ptr< ::circleFinder::circleEntry const> circleEntryConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::circleFinder::circleEntry_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::circleFinder::circleEntry_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace circleFinder

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::circleFinder::circleEntry_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8f570732ed87e134eeda1a3829552b4e";
  }

  static const char* value(const  ::circleFinder::circleEntry_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x8f570732ed87e134ULL;
  static const uint64_t static_value2 = 0xeeda1a3829552b4eULL;
};

template<class ContainerAllocator>
struct DataType< ::circleFinder::circleEntry_<ContainerAllocator> > {
  static const char* value() 
  {
    return "circleFinder/circleEntry";
  }

  static const char* value(const  ::circleFinder::circleEntry_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::circleFinder::circleEntry_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 x\n\
float32 y\n\
float32 distance\n\
float32 theta\n\
float32 radius\n\
\n\
";
  }

  static const char* value(const  ::circleFinder::circleEntry_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::circleFinder::circleEntry_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::circleFinder::circleEntry_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.distance);
    stream.next(m.theta);
    stream.next(m.radius);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct circleEntry_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::circleFinder::circleEntry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::circleFinder::circleEntry_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "radius: ";
    Printer<float>::stream(s, indent + "  ", v.radius);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CIRCLEFINDER_MESSAGE_CIRCLEENTRY_H

