"""autogenerated by genmsg_py from circleEntry.msg. Do not edit."""
import roslib.message
import struct


class circleEntry(roslib.message.Message):
  _md5sum = "8f570732ed87e134eeda1a3829552b4e"
  _type = "circleFinder/circleEntry"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 x
float32 y
float32 distance
float32 theta
float32 radius

"""
  __slots__ = ['x','y','distance','theta','radius']
  _slot_types = ['float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       x,y,distance,theta,radius
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(circleEntry, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.distance is None:
        self.distance = 0.
      if self.theta is None:
        self.theta = 0.
      if self.radius is None:
        self.radius = 0.
    else:
      self.x = 0.
      self.y = 0.
      self.distance = 0.
      self.theta = 0.
      self.radius = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_5f.pack(_x.x, _x.y, _x.distance, _x.theta, _x.radius))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.x, _x.y, _x.distance, _x.theta, _x.radius,) = _struct_5f.unpack(str[start:end])
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_5f.pack(_x.x, _x.y, _x.distance, _x.theta, _x.radius))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.x, _x.y, _x.distance, _x.theta, _x.radius,) = _struct_5f.unpack(str[start:end])
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_5f = struct.Struct("<5f")
