/* Auto-generated by genmsg_cpp for file /home/rcle271/ros_workspace/circleFilter/msg/coordinate.msg */
#ifndef CIRCLEFILTER_MESSAGE_COORDINATE_H
#define CIRCLEFILTER_MESSAGE_COORDINATE_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace circleFilter
{
template <class ContainerAllocator>
struct coordinate_ : public ros::Message
{
  typedef coordinate_<ContainerAllocator> Type;

  coordinate_()
  : x(0.0)
  , y(0.0)
  , theta(0.0)
  , beaconcount(0)
  {
  }

  coordinate_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , theta(0.0)
  , beaconcount(0)
  {
  }

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _theta_type;
  double theta;

  typedef int8_t _beaconcount_type;
  int8_t beaconcount;


private:
  static const char* __s_getDataType_() { return "circleFilter/coordinate"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "fa83e32d0048a022a60f823f2d5ea524"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 x\n\
float64 y\n\
float64 theta\n\
int8 beaconcount\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, x);
    ros::serialization::serialize(stream, y);
    ros::serialization::serialize(stream, theta);
    ros::serialization::serialize(stream, beaconcount);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, x);
    ros::serialization::deserialize(stream, y);
    ros::serialization::deserialize(stream, theta);
    ros::serialization::deserialize(stream, beaconcount);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(x);
    size += ros::serialization::serializationLength(y);
    size += ros::serialization::serializationLength(theta);
    size += ros::serialization::serializationLength(beaconcount);
    return size;
  }

  typedef boost::shared_ptr< ::circleFilter::coordinate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::circleFilter::coordinate_<ContainerAllocator>  const> ConstPtr;
}; // struct coordinate
typedef  ::circleFilter::coordinate_<std::allocator<void> > coordinate;

typedef boost::shared_ptr< ::circleFilter::coordinate> coordinatePtr;
typedef boost::shared_ptr< ::circleFilter::coordinate const> coordinateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::circleFilter::coordinate_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::circleFilter::coordinate_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace circleFilter

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::circleFilter::coordinate_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fa83e32d0048a022a60f823f2d5ea524";
  }

  static const char* value(const  ::circleFilter::coordinate_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xfa83e32d0048a022ULL;
  static const uint64_t static_value2 = 0xa60f823f2d5ea524ULL;
};

template<class ContainerAllocator>
struct DataType< ::circleFilter::coordinate_<ContainerAllocator> > {
  static const char* value() 
  {
    return "circleFilter/coordinate";
  }

  static const char* value(const  ::circleFilter::coordinate_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::circleFilter::coordinate_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 x\n\
float64 y\n\
float64 theta\n\
int8 beaconcount\n\
\n\
";
  }

  static const char* value(const  ::circleFilter::coordinate_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::circleFilter::coordinate_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::circleFilter::coordinate_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.theta);
    stream.next(m.beaconcount);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct coordinate_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::circleFilter::coordinate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::circleFilter::coordinate_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
    s << indent << "beaconcount: ";
    Printer<int8_t>::stream(s, indent + "  ", v.beaconcount);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CIRCLEFILTER_MESSAGE_COORDINATE_H

